--------------------------------------------------------
--  File created - среда-февраля-21-2018   
--------------------------------------------------------
DROP TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."CONTENT_STRING" cascade constraints;
DROP TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."DISH" cascade constraints;
DROP TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."PRODUCT_IN_RESTAURANT" cascade constraints;
--------------------------------------------------------
--  DDL for Table CONTENT_STRING
--------------------------------------------------------

  CREATE TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."CONTENT_STRING" 
   (	"PRODUCT_ID" NUMBER, 
	"DISH_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
--------------------------------------------------------
--  DDL for Table DISH
--------------------------------------------------------

  CREATE TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."DISH" 
   (	"DISH_ID" NUMBER(4,0), 
	"DISH_NAME" VARCHAR2(100 BYTE), 
	"DISH_PRICE" NUMBER(5,2), 
	"AVAILEBLE" NUMBER(1,0), 
	"WEIGHT" NUMBER, 
	"DISH_TYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
--------------------------------------------------------
--  DDL for Table PRODUCT_IN_RESTAURANT
--------------------------------------------------------

  CREATE TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."PRODUCT_IN_RESTAURANT" 
   (	"PRODUCT_ID" NUMBER(4,0), 
	"AVAILEBLE" NUMBER(1,0), 
	"AMOUNT" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
REM INSERTING into BOGDANOVA_ADAMCHUK_RESTAURANT.CONTENT_STRING
SET DEFINE OFF;
