--------------------------------------------------------
--  File created - среда-февраля-21-2018   
--------------------------------------------------------
DROP TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."DISH" cascade constraints;
--------------------------------------------------------
--  DDL for Table DISH
--------------------------------------------------------

  CREATE TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."DISH" 
   (	"DISH_ID" NUMBER(4,0), 
	"DISH_NAME" VARCHAR2(100 BYTE), 
	"DISH_PRICE" NUMBER(5,2), 
	"AVAILEBLE" NUMBER(1,0), 
	"WEIGHT" NUMBER, 
	"DISH_TYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
REM INSERTING into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH
SET DEFINE OFF;
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('1','Харчо','3,5','1','450','Первое');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('2','Пицца','6,07','1','500','Пицца');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('3','Барская','5,08','0','300','Пицца');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('4','Кофе эспрессо','4,06','1','75','Горячий напиток');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('5','Закуска под водочку','4,77','1','200','Холодная закуска');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('6','Овощная нарезка','5,21','1','304','Холодная закуска');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('7','Бутерброд с семгой','3,08','0','55','Холодная закуска');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('8','Бутерброд с красной икрой','3,63','1','50','Холодная закуска');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('9','Мясная нарезка','7,2','1','203','Холодная закуска');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('10','Помидоры с сыром и чесноком','3,89','1','180','Холодная закуска');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('11','Баклажаны фаршированные','3,1','1','100','Горячая закуска');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('12','Блины с семгой','5,21','0','148','Горячая закуска');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('13','Блины с красной икрой','5,05','1','128','Горячая закуска');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('14','Жульен из птицы','4,2','1','105','Горячая закуска');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('24','Салат оригинальный','3,3','1','150','Салат');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('15','Греческий','4,93','1','210','Салат');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('16','Салат из свежей капуста с перцем','3,33','0','220','Салат');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('17','Царское угощение','6,27','1','160','Салат');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('18','Салат с говядиной','3,37','1','150','Салат');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('19','Салат с ананасами','2,94','1','160','Салат');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('20','Морское чудо','5,74','1','130','Салат');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('21','Мужской каприз','5,93','1','160','Салат');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('22','С курочкой и миндалем','4,51','1','160','Салат');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('23','Белорусский с печенью','3,7','1','190','Салат');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('25','Уха по-русски','3,89','1','300','Первое');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('26','Солянка сборная мясная','3,43','1','330','Первое');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('27','Суп-пюре из тыквы','2,27','1','250','Первое');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('28','Суп грибной','2,86','1','350','Первое');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('29','Борщ холодный','2,2','1','400','Первое');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('30','Овощи на гарнир','1,28','1','100','Гарнир');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('31','Салат из семги с томатами','6,69','0','150','Салат');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('32','Овощи жареные','3,5','1','130','Гарнир');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('33','Овощи по-домашнему','2,61','1','160','Гарнир');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('34','Картофель фри','1,6','1','153','Гарнир');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('35','Картофельные дольки с салатом из свежей капусты','2,65','1','300','Гарнир');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('36','Стейк из форели','14,29','1','200','Горячее');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('37','Сковородка фермера','7,8','1','350','Горячее');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('38','Свиная корейка под соусом хрен','9,14','1','250','Горячее');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('39','Свинина запеченая с грибами','8,22','1','230','Горячее');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('40','Шашлык куриный','6,9','1','230','Горячее');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('41','Куриное филе запеченое с томатом','4,98','1','230','Горячее');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('42','Драники с мясом в горшочке','7,4','1','250','Горячее');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('43','Треска запеченая с брокколи','7,67','1','250','Горячее');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('44','Скумбрия запеченая','6,04','1','200','Горячее');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('45','Форель в сливочном соусе','12,56','1','270','Горячее');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('46','Говядина под соусом сациви','8,4','1','210','Горячее');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('47','Блины с картофелем и грибами','3,26','1','230','Горячая закуска');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('48','Мороженое "Сладкий поцелуй"','2,77','1','155','Десерт');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('49','Мороженое с сиропом','2,85','1','170','Десерт');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('50','Мороженое с фруктами','2,87','1','170','Десерт');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('51','Мороженое "Вишенка"','2,37','1','135','Десерт');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('52','Блинчики с мороженым и ягодным миксом','3,34','1','240','Десерт');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('53','Фруктовое ассорти','5,43','0','500','Десерт');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('54','Блины с бананами и сиропом','2,16','1','210','Десерт');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('55','Блины с джемом','1,67','1','155','Десерт');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('56','Блины с медом','0,99','1','130','Десерт');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('57','Блины со сметанным соусом и ананасами','2,45','1','170','Десерт');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('58','Кофе американо','2,24','1','200','Горячий напиток');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('59','Кофе гляссе','2,62','1','75','Горячий напиток');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('60','Капучино','2,44','1','200','Горячий напиток');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('61','Чай','1','1','250','Горячий напиток');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('62','Молочный коктейль банановый','2,74','1','350','Молочный коктейль');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('63','Молочный коктейль с сиропом','2,4','1','350','Молочный коктейль');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('64','Молочный коктейль с шоколадом','2,4','1','350','Молочный коктейль');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('65','Молочный коктейль с фантой','2,43','1','350','Молочный коктейль');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('66','Молочный коктейль с кока-колой','2,43','1','350','Молочный коктейль');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('67','Молочный коктейль со спрайтом','2,43','1','350','Молочный коктейль');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('68',' Молочный коктейль с соком','2,22','1','350','Молочный коктейль');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('69','Свежевыжатый яблочный сок','3,6','1','300','Свежевыжатый сок');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('70','Свежевыжатый сок яблочно-апельсиновый','4,1','1','300','Свежевыжатый сок');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('71','Свежевыжатый сок яблочно-морковный','3','1','300','Свежевыжатый сок');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('72',' Свежевыжатый сок морковный','1,8','1','300','Свежевыжатый сок');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('73','Свежевыжатый сок морковно-свекольный','2,1','1','300','Свежевыжатый сок');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('74','Свежевыжатый сок свекольно-морковно-яблочный','2,4','1','300','Свежевыжатый сок');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('75','Пицца Маргарита','5,23','1','360','Пицца');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('76','Пицца Студенческая','6,38','1','380','Пицца');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('77','Пицца Сытная','7,2','1','410','Пицца');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('78','Пицца Лёгкая','6,88','1','340','Пицца');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('79','Пицца Морская','10,54','1','415','Пицца');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('80','Пицца Острая','8,87','1','390','Пицца');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('81','Пицца К пиву','7,93','1','400','Пицца');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('82','Пицца Домашняя','8,24','1','430','Пицца');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('83','Пицца Аппетитная','7,72','1','430','Пицца');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('84','Пицца Тоскана','7,47','1','430','Пицца');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('85','Пицца Бергамо','7,6','1','380','Пицца');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('86','Пицца Барбекю','6,71','1','360','Пицца');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('87','Пицца Техас','6,79','1','380','Пицца');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('88',' Пицца Деревенская','7,11','1','400','Пицца');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('89','Пицца  Везувий','7,73','1','400','Пицца');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('90','Пицца Овощная','6,53','1','420','Пицца');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('91',' Пицца Купеческая','8','1','520','Пицца');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('92','Пицца Десертная','8,28','1','530','Пицца');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.DISH (DISH_ID,DISH_NAME,DISH_PRICE,AVAILEBLE,WEIGHT,DISH_TYPE) values ('93','Пицца Венеция','8,57','1','430','Пицца');
--------------------------------------------------------
--  DDL for Index DISH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOGDANOVA_ADAMCHUK_RESTAURANT"."DISH_PK" ON "BOGDANOVA_ADAMCHUK_RESTAURANT"."DISH" ("DISH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
--------------------------------------------------------
--  Constraints for Table DISH
--------------------------------------------------------

  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."DISH" ADD CONSTRAINT "DISH_PK" PRIMARY KEY ("DISH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT"  ENABLE;
  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."DISH" MODIFY ("AVAILEBLE" NOT NULL ENABLE);
  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."DISH" MODIFY ("DISH_PRICE" NOT NULL ENABLE);
  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."DISH" MODIFY ("DISH_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."DISH" MODIFY ("DISH_ID" NOT NULL ENABLE);
  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."DISH" MODIFY ("DISH_TYPE" NOT NULL ENABLE);
