--------------------------------------------------------
--  File created - среда-февраля-21-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FINANCE
--------------------------------------------------------

  CREATE TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."FINANCE" 
   (	"DEPARTMENT_ID" NUMBER, 
	"DATE_ID" VARCHAR2(20 BYTE), 
	"INCOME" NUMBER, 
	"OUTCOME" NUMBER, 
	"MARGIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
REM INSERTING into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE
SET DEFINE OFF;
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('1','20170102','10','5','5');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('1','20170120','20','5','15');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('1','20170215','30','5','25');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('1','20170228','40','5','35');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('1','20170224','50','5','45');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('1','20170309','50','5','45');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('1','20170311','10','5','5');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('1','20170415','30','5','25');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('1','20170422','40','5','35');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('1','20170503','50','5','45');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('1','20170609','60','5','55');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('1','20170708','70','5','65');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('1','20170810','40','5','35');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('1','20170917','30','5','25');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('1','20171002','40','5','35');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('1','20171103','20','5','15');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('1','20171206','50','5','45');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('1','20171105','60','5','55');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('2','20171103','34','5','29');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('3','20171121','67','5','62');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('4','20171125','65','5','60');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('4','20171130','74','5','69');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('5','20171125','85','5','80');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.FINANCE (DEPARTMENT_ID,DATE_ID,INCOME,OUTCOME,MARGIN) values ('3','20171126','73','5','68');
