--------------------------------------------------------
--  File created - среда-февраля-21-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table JOBS
--------------------------------------------------------

  CREATE TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."JOBS" 
   (	"JOB_ID" VARCHAR2(10 BYTE), 
	"JOB_TITLE" VARCHAR2(35 BYTE), 
	"MIN_SALARY" NUMBER(6,0), 
	"MAX_SALARY" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;

   COMMENT ON COLUMN "BOGDANOVA_ADAMCHUK_RESTAURANT"."JOBS"."JOB_ID" IS 'Primary key of jobs table.';
   COMMENT ON COLUMN "BOGDANOVA_ADAMCHUK_RESTAURANT"."JOBS"."JOB_TITLE" IS 'A not null column that shows job title, e.g. AD_VP, FI_ACCOUNTANT';
   COMMENT ON COLUMN "BOGDANOVA_ADAMCHUK_RESTAURANT"."JOBS"."MIN_SALARY" IS 'Minimum salary for a job title.';
   COMMENT ON COLUMN "BOGDANOVA_ADAMCHUK_RESTAURANT"."JOBS"."MAX_SALARY" IS 'Maximum salary for a job title';
   COMMENT ON TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."JOBS"  IS 'jobs table with job titles and salary ranges. Contains 19 rows.
References with employees and job_history table.';
REM INSERTING into BOGDANOVA_ADAMCHUK_RESTAURANT.JOBS
SET DEFINE OFF;
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) values ('1','Администратор','200','500');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) values ('2','Официант','100','400');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) values ('3','Повар','200','600');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) values ('4','Бухгалтер','300','700');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) values ('5','Складовщик','200','400');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) values ('6','Доп. персонал','50','300');
--------------------------------------------------------
--  DDL for Index JOB_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOGDANOVA_ADAMCHUK_RESTAURANT"."JOB_ID_PK" ON "BOGDANOVA_ADAMCHUK_RESTAURANT"."JOBS" ("JOB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
--------------------------------------------------------
--  Constraints for Table JOBS
--------------------------------------------------------

  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."JOBS" MODIFY ("JOB_TITLE" CONSTRAINT "JOB_TITLE_NN" NOT NULL ENABLE);
  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."JOBS" ADD CONSTRAINT "JOB_ID_PK" PRIMARY KEY ("JOB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT"  ENABLE;
