--------------------------------------------------------
--  File created - среда-февраля-21-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LOGIN
--------------------------------------------------------

  CREATE TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."LOGIN" 
   (	"LOGIN_ID" NUMBER(4,0), 
	"LOGIN" VARCHAR2(20 BYTE), 
	"PASWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
REM INSERTING into BOGDANOVA_ADAMCHUK_RESTAURANT.LOGIN
SET DEFINE OFF;
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.LOGIN (LOGIN_ID,LOGIN,PASWORD) values ('8','2','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.LOGIN (LOGIN_ID,LOGIN,PASWORD) values ('9','3','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.LOGIN (LOGIN_ID,LOGIN,PASWORD) values ('10','4','4');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.LOGIN (LOGIN_ID,LOGIN,PASWORD) values ('11','5','5');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.LOGIN (LOGIN_ID,LOGIN,PASWORD) values ('1','Админ','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.LOGIN (LOGIN_ID,LOGIN,PASWORD) values ('2','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.LOGIN (LOGIN_ID,LOGIN,PASWORD) values ('3','Кухня','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.LOGIN (LOGIN_ID,LOGIN,PASWORD) values ('4','Официант','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.LOGIN (LOGIN_ID,LOGIN,PASWORD) values ('5','Кухня','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.LOGIN (LOGIN_ID,LOGIN,PASWORD) values ('6','Бухгалтер','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.LOGIN (LOGIN_ID,LOGIN,PASWORD) values ('7','Склад','1');
--------------------------------------------------------
--  DDL for Index LOGIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOGDANOVA_ADAMCHUK_RESTAURANT"."LOGIN_PK" ON "BOGDANOVA_ADAMCHUK_RESTAURANT"."LOGIN" ("LOGIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
--------------------------------------------------------
--  Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."LOGIN" ADD CONSTRAINT "LOGIN_PK" PRIMARY KEY ("LOGIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT"  ENABLE;
  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."LOGIN" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
