--------------------------------------------------------
--  File created - среда-февраля-21-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDER_STRING
--------------------------------------------------------

  CREATE TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."ORDER_STRING" 
   (	"ORDER_ID" NUMBER(4,0), 
	"DISH_ID" NUMBER(4,0), 
	"AMOUNT_OF_PLATES" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
REM INSERTING into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING
SET DEFINE OFF;
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('1','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('2','44','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('2','78','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('1','34','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('1','72','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('3','11','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('3','33','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('3','4','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('8','6','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('8','5','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('8','2','5');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('8','10','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('8','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('8','11','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('8','15','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('8','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('8','5','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('8','4','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('8','12','7');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('8','40','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('8','4','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('8','7','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('4','27','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('4','13','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('4','50','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('4','59','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_STRING (ORDER_ID,DISH_ID,AMOUNT_OF_PLATES) values ('4','60','1');
