--------------------------------------------------------
--  File created - среда-февраля-21-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDER_
--------------------------------------------------------

  CREATE TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."ORDER_" 
   (	"ORDER_ID" NUMBER(4,0), 
	"DATE_ID" VARCHAR2(8 BYTE), 
	"TIME" VARCHAR2(8 BYTE), 
	"STUFF_ID" NUMBER(4,0), 
	"TABLE_ID" NUMBER(4,0), 
	"TOTAL_PRICE" NUMBER, 
	"STATUS" VARCHAR2(50 BYTE) DEFAULT 'Обрабатывается'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
REM INSERTING into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_
SET DEFINE OFF;
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_ (ORDER_ID,DATE_ID,TIME,STUFF_ID,TABLE_ID,TOTAL_PRICE,STATUS) values ('6','20171122','15:46','4','2','50','Оплачен');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_ (ORDER_ID,DATE_ID,TIME,STUFF_ID,TABLE_ID,TOTAL_PRICE,STATUS) values ('9','20171206','22:40','4','1','23,46','Оплачен');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_ (ORDER_ID,DATE_ID,TIME,STUFF_ID,TABLE_ID,TOTAL_PRICE,STATUS) values ('10','20171210','17:02','2','2','14,04','Выполнен');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_ (ORDER_ID,DATE_ID,TIME,STUFF_ID,TABLE_ID,TOTAL_PRICE,STATUS) values ('11','20171203','12:20','2','3','118,42','Оплачен');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_ (ORDER_ID,DATE_ID,TIME,STUFF_ID,TABLE_ID,TOTAL_PRICE,STATUS) values ('12','20171202',null,'2','1','32,43','Оплачен');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_ (ORDER_ID,DATE_ID,TIME,STUFF_ID,TABLE_ID,TOTAL_PRICE,STATUS) values ('13','20171210','13:23','4','2','16,38','Оплачен');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_ (ORDER_ID,DATE_ID,TIME,STUFF_ID,TABLE_ID,TOTAL_PRICE,STATUS) values ('14','20171203',null,'4','3','32','Оплачен');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_ (ORDER_ID,DATE_ID,TIME,STUFF_ID,TABLE_ID,TOTAL_PRICE,STATUS) values ('15','20171125',null,'4','1','45','Оплачен');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_ (ORDER_ID,DATE_ID,TIME,STUFF_ID,TABLE_ID,TOTAL_PRICE,STATUS) values ('1','20171210','13:00','4','1','10','Выполнен');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_ (ORDER_ID,DATE_ID,TIME,STUFF_ID,TABLE_ID,TOTAL_PRICE,STATUS) values ('2','20171210','15:40','4','2','20','Готовится');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_ (ORDER_ID,DATE_ID,TIME,STUFF_ID,TABLE_ID,TOTAL_PRICE,STATUS) values ('3','20171101','08:37','4','3','30','Оплачен');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_ (ORDER_ID,DATE_ID,TIME,STUFF_ID,TABLE_ID,TOTAL_PRICE,STATUS) values ('4','20171121','10:48','4','1','55,24999999999999','Оплачен');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_ (ORDER_ID,DATE_ID,TIME,STUFF_ID,TABLE_ID,TOTAL_PRICE,STATUS) values ('5','20171117','18:20','2','1','50','Оплачен');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_ (ORDER_ID,DATE_ID,TIME,STUFF_ID,TABLE_ID,TOTAL_PRICE,STATUS) values ('7','20171125','13:45','2','1','95','Оплачен');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.ORDER_ (ORDER_ID,DATE_ID,TIME,STUFF_ID,TABLE_ID,TOTAL_PRICE,STATUS) values ('8','20171125','15:30','4','2','54,69','Оплачен');
--------------------------------------------------------
--  DDL for Index ORDER__PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOGDANOVA_ADAMCHUK_RESTAURANT"."ORDER__PK" ON "BOGDANOVA_ADAMCHUK_RESTAURANT"."ORDER_" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
--------------------------------------------------------
--  Constraints for Table ORDER_
--------------------------------------------------------

  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."ORDER_" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."ORDER_" ADD CONSTRAINT "ORDER__PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT"  ENABLE;
