--------------------------------------------------------
--  File created - среда-февраля-21-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCT_IN_RESTAURANT
--------------------------------------------------------

  CREATE TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."PRODUCT_IN_RESTAURANT" 
   (	"PRODUCT_ID" NUMBER(4,0), 
	"AVAILEBLE" NUMBER(1,0), 
	"AMOUNT" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
REM INSERTING into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT
SET DEFINE OFF;
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('1','1','340');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('2','1','254');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('3','1','543');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('4','1','673');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('5','1','3456');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('6','1','768');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('7','1','436');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('8','1','443');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('9','1','353');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('10','1','124');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('11','1','236');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('12','1','236');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('13','1','356');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('14','1','432');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('15','1','343');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('16','1','376');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('17','1','348');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('18','1','345');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('19','1','346');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('20','1','4436');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('21','1','387');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('22','1','354');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('23','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('24','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('25','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('26','1','22');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('27','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('28','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('29','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('30','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('31','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('32','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('33','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('34','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('35','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('36','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('37','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('38','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('39','0','22');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('40','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('41','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('42','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('43','0','22');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('44','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('45','0','22');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('46','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('47','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('48','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('49','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('50','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('51','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('52','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('53','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('54','0','22');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('55','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('56','0','22');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('57','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('58','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('59','0','22');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('60','0','22');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('61','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('62','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('63','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('64','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('65','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('66','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('67','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('68','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('69','1','22');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('70','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('71','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('72','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('73','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('74','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('75','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('76','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('77','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('78','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('79','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_IN_RESTAURANT (PRODUCT_ID,AVAILEBLE,AMOUNT) values ('80','1','2');
--------------------------------------------------------
--  DDL for Index PRODUCT_IN_RESTAURANT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOGDANOVA_ADAMCHUK_RESTAURANT"."PRODUCT_IN_RESTAURANT_PK" ON "BOGDANOVA_ADAMCHUK_RESTAURANT"."PRODUCT_IN_RESTAURANT" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
--------------------------------------------------------
--  Constraints for Table PRODUCT_IN_RESTAURANT
--------------------------------------------------------

  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."PRODUCT_IN_RESTAURANT" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."PRODUCT_IN_RESTAURANT" ADD CONSTRAINT "PRODUCT_IN_RESTAURANT_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT"  ENABLE;
