--------------------------------------------------------
--  File created - среда-февраля-21-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."PRODUCT" 
   (	"PRODUCT_ID" NUMBER(4,0), 
	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"PRICE" NUMBER(4,0), 
	"MEASURE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
REM INSERTING into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT
SET DEFINE OFF;
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('1','Аджика','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('2','Баклажаны','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('3','Бананы','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('4','Батон','33','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('5','Блины','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('6','Брокколи','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('7','Брынза','33','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('8','Булочка','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('9','Ветчина','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('10','Вырезка свиная','33','гг');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('11','Горчица','8','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('12','Гренки','8','гг');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('13','Драники','8','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('14','Зелень','8','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('15','Кальмары','8','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('16','Капуста цветная','8','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('17','Картофельные дольки','78','гг');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('18','Картофель','7','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('19','Кетчуп','7','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('20','Кокосовая стружка','7','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('21','Колбоса с/к','7','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('22','Корень имбиря','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('23','Корица','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('24','Котлета','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('25','Креветки','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('26','Лимон','3','гг');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('27','Лук зеленый','3','гг');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('28','Лук репчатый','3','гг');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('29','Майонез','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('30','Макароны','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('31','Маслины','33','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('32','Масло растительное','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('33','Масло сливочное','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('34','Молоко','5','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('35','Морковь','5','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('36','Мука','5','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('37','Наггетсы','5','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('38','Огурец консервированный','5','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('39','Огурец свежий','5','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('40','Арахис','5','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('41','Паста томатная','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('42','Миндаль','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('43','Грецкий орех','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('44','Паста томатная','33','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('45','Перец болгарский','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('46','Перец молотый','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('47','Помидоры','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('48','Рулет к/в','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('49','Салат','4','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('50','Сахар','44','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('51','Свекла','4','гг');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('52','Свинина','44','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('53','Семга сл/сол','4','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('54','Семечки подсолнечника','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('55','Сливки','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('56','Сметана','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('57','Соль','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('58','Сосиски','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('59','Соус китайский','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('60','Специи','3','гг');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('61','Сухарики','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('62','Сыр мацарела','4','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('63','Сыр плавленный','4','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('64','Тыква','4','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('65','Уксус бальзамический','4','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('66','Фарш свиной','33','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('67','Фасоль консервированная','4','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('68','Филе куриное','4','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('69','Филе трески','4','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('70','Картошка фри','4','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('71','Хрен','4','гг');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('72','Чернослив','4','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('73','Чеснок','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('74','Шампиньоны','3','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('75','Шоколад','4','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('76','Шпинат','4','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('77','Яйцо куриное','44','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('78','Яйцо перепелиное','4','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('79','Тесто слоеное','4','г');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,MEASURE) values ('80','Соус томатный','44','г');
--------------------------------------------------------
--  DDL for Index PRODUCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOGDANOVA_ADAMCHUK_RESTAURANT"."PRODUCT_PK" ON "BOGDANOVA_ADAMCHUK_RESTAURANT"."PRODUCT" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."PRODUCT" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."PRODUCT" ADD CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT"  ENABLE;
