--------------------------------------------------------
--  File created - среда-февраля-21-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCT_ON_STOCK
--------------------------------------------------------

  CREATE TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."PRODUCT_ON_STOCK" 
   (	"PRODUCT_ID" NUMBER(8,0), 
	"AVAILEBLE" NUMBER(7,0) DEFAULT 0, 
	"RACK_ID" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
REM INSERTING into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK
SET DEFINE OFF;
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('1','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('2','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('3','1','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('4','1','4');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('5','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('6','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('7','1','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('8','1','4');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('9','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('10','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('11','1','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('12','1','4');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('13','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('14','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('15','1','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('16','1','4');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('17','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('18','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('19','1','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('20','1','4');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('21','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('22','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('23','1','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('24','0','4');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('25','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('26','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('27','1','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('28','1','4');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('29','0','4');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('30','0','4');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('31','0','4');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('32','0','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('33','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('34','0','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('35','0','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('36','0','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('37','1','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('38','1','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('39','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('40','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('41','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('42','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('43','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('44','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('45','1','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('46','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('47','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('48','1','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('49','1','4');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('50','1','4');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('51','1','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('52','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('53','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('54','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('55','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('56','1','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('57','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('58','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('59','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('60','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('61','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('62','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('63','1','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('64','1','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('65','1','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('66','1','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('67','1','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('68','0','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('69','0','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('70','0','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('71','0','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('72','0','4');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('73','0','4');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('74','0','3');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('75','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('76','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('77','1','1');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('78','1','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.PRODUCT_ON_STOCK (PRODUCT_ID,AVAILEBLE,RACK_ID) values ('79','1','3');
--------------------------------------------------------
--  DDL for Index PRODUCT_ON_STOCK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOGDANOVA_ADAMCHUK_RESTAURANT"."PRODUCT_ON_STOCK_PK" ON "BOGDANOVA_ADAMCHUK_RESTAURANT"."PRODUCT_ON_STOCK" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
--------------------------------------------------------
--  Constraints for Table PRODUCT_ON_STOCK
--------------------------------------------------------

  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."PRODUCT_ON_STOCK" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."PRODUCT_ON_STOCK" ADD CONSTRAINT "PRODUCT_ON_STOCK_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT"  ENABLE;
