--------------------------------------------------------
--  File created - среда-февраля-21-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RACK
--------------------------------------------------------

  CREATE TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."RACK" 
   (	"RACK_ID" NUMBER(4,0), 
	"CAPACITY" NUMBER(6,0), 
	"FULLNESS" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
REM INSERTING into BOGDANOVA_ADAMCHUK_RESTAURANT.RACK
SET DEFINE OFF;
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.RACK (RACK_ID,CAPACITY,FULLNESS) values ('1','5','4');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.RACK (RACK_ID,CAPACITY,FULLNESS) values ('2','10','4');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.RACK (RACK_ID,CAPACITY,FULLNESS) values ('3','35','4');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.RACK (RACK_ID,CAPACITY,FULLNESS) values ('4','54','25');
--------------------------------------------------------
--  DDL for Index RACK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOGDANOVA_ADAMCHUK_RESTAURANT"."RACK_PK" ON "BOGDANOVA_ADAMCHUK_RESTAURANT"."RACK" ("RACK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
--------------------------------------------------------
--  Constraints for Table RACK
--------------------------------------------------------

  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."RACK" MODIFY ("RACK_ID" NOT NULL ENABLE);
  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."RACK" ADD CONSTRAINT "RACK_PK" PRIMARY KEY ("RACK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT"  ENABLE;
