--------------------------------------------------------
--  File created - среда-февраля-21-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SALARY
--------------------------------------------------------

  CREATE TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."SALARY" 
   (	"SALARY" NUMBER DEFAULT 0, 
	"STUFF_ID" NUMBER(4,0), 
	"DATE_KEY" VARCHAR2(8 BYTE), 
	"DEDUCATION" NUMBER(8,0) DEFAULT 0, 
	"INCOME" NUMBER(4,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
REM INSERTING into BOGDANOVA_ADAMCHUK_RESTAURANT.SALARY
SET DEFINE OFF;
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.SALARY (SALARY,STUFF_ID,DATE_KEY,DEDUCATION,INCOME) values ('100','7','20171101','20','120');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.SALARY (SALARY,STUFF_ID,DATE_KEY,DEDUCATION,INCOME) values ('30','1','20171101','20','50');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.SALARY (SALARY,STUFF_ID,DATE_KEY,DEDUCATION,INCOME) values ('70','2','20171101','0','70');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.SALARY (SALARY,STUFF_ID,DATE_KEY,DEDUCATION,INCOME) values ('7','3','20171101','53','60');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.SALARY (SALARY,STUFF_ID,DATE_KEY,DEDUCATION,INCOME) values ('210','4','20171101','0','210');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.SALARY (SALARY,STUFF_ID,DATE_KEY,DEDUCATION,INCOME) values ('270','5','20171101','30','300');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.SALARY (SALARY,STUFF_ID,DATE_KEY,DEDUCATION,INCOME) values ('80','7','20171201','60','140');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.SALARY (SALARY,STUFF_ID,DATE_KEY,DEDUCATION,INCOME) values ('45','1','20171201','45','90');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.SALARY (SALARY,STUFF_ID,DATE_KEY,DEDUCATION,INCOME) values ('145','2','20171201','0','145');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.SALARY (SALARY,STUFF_ID,DATE_KEY,DEDUCATION,INCOME) values ('19','3','20171201','41','400');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.SALARY (SALARY,STUFF_ID,DATE_KEY,DEDUCATION,INCOME) values ('400','4','20171201','0','400');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.SALARY (SALARY,STUFF_ID,DATE_KEY,DEDUCATION,INCOME) values ('70','5','20171201','0','70');
--------------------------------------------------------
--  DDL for Index SALARY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOGDANOVA_ADAMCHUK_RESTAURANT"."SALARY_PK" ON "BOGDANOVA_ADAMCHUK_RESTAURANT"."SALARY" ("STUFF_ID", "DATE_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
--------------------------------------------------------
--  Constraints for Table SALARY
--------------------------------------------------------

  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."SALARY" ADD CONSTRAINT "SALARY_PK" PRIMARY KEY ("STUFF_ID", "DATE_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT"  ENABLE;
  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."SALARY" MODIFY ("DATE_KEY" NOT NULL ENABLE);
  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."SALARY" MODIFY ("STUFF_ID" NOT NULL ENABLE);
