--------------------------------------------------------
--  File created - среда-февраля-21-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STUFF
--------------------------------------------------------

  CREATE TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."STUFF" 
   (	"STUFF_ID" NUMBER(4,0), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"JOB_ID" VARCHAR2(20 BYTE), 
	"DEPARTMENT_ID" NUMBER(4,0), 
	"MANAGER_ID" NUMBER(4,0), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"LOGIN_ID" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
REM INSERTING into BOGDANOVA_ADAMCHUK_RESTAURANT.STUFF
SET DEFINE OFF;
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.STUFF (STUFF_ID,FIRST_NAME,LAST_NAME,JOB_ID,DEPARTMENT_ID,MANAGER_ID,PHONE_NUMBER,LOGIN_ID) values ('7','Анна','Ахматова','5','1','1',null,'10');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.STUFF (STUFF_ID,FIRST_NAME,LAST_NAME,JOB_ID,DEPARTMENT_ID,MANAGER_ID,PHONE_NUMBER,LOGIN_ID) values ('6','Блок','Евгений','3','1','1',null,'9');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.STUFF (STUFF_ID,FIRST_NAME,LAST_NAME,JOB_ID,DEPARTMENT_ID,MANAGER_ID,PHONE_NUMBER,LOGIN_ID) values ('1','Юрий','Адамчук','1','7','1','80296149555','6');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.STUFF (STUFF_ID,FIRST_NAME,LAST_NAME,JOB_ID,DEPARTMENT_ID,MANAGER_ID,PHONE_NUMBER,LOGIN_ID) values ('2','Юрий','Стрыкало','2','1','1','80295462822','4');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.STUFF (STUFF_ID,FIRST_NAME,LAST_NAME,JOB_ID,DEPARTMENT_ID,MANAGER_ID,PHONE_NUMBER,LOGIN_ID) values ('3','Екатерина','Лава','1','1','1','80295674433','2');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.STUFF (STUFF_ID,FIRST_NAME,LAST_NAME,JOB_ID,DEPARTMENT_ID,MANAGER_ID,PHONE_NUMBER,LOGIN_ID) values ('4','Максим','Жванецкий','2','1','1','80299876543','8');
Insert into BOGDANOVA_ADAMCHUK_RESTAURANT.STUFF (STUFF_ID,FIRST_NAME,LAST_NAME,JOB_ID,DEPARTMENT_ID,MANAGER_ID,PHONE_NUMBER,LOGIN_ID) values ('5','Галина','Адамчук','4','6','1','80296149555','11');
--------------------------------------------------------
--  DDL for Index STUFF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOGDANOVA_ADAMCHUK_RESTAURANT"."STUFF_PK" ON "BOGDANOVA_ADAMCHUK_RESTAURANT"."STUFF" ("STUFF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT" ;
--------------------------------------------------------
--  Constraints for Table STUFF
--------------------------------------------------------

  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."STUFF" MODIFY ("STUFF_ID" NOT NULL ENABLE);
  ALTER TABLE "BOGDANOVA_ADAMCHUK_RESTAURANT"."STUFF" ADD CONSTRAINT "STUFF_PK" PRIMARY KEY ("STUFF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOGDANOVA_ADAMCHUK_RESTAURANT"  ENABLE;
