create USER  BOGDANOVA_ADAMCHUK_RESTAURANT IDENTIFIED BY Q1w2e3r4;
grant all PRIVILEGES to  BOGDANOVA_ADAMCHUK_RESTAURANT;
  DROP  USER BOGDANOVA_ADAMCHUK_RESTAURANT  CASCADE;
  
  CREATE TABLESPACE BOGDANOVA_ADAMCHUK_RESTAURANT
    DATAFILE 
        'DWH_BOGDANOVA_ADAMCHUK_RESTAURANT_001.DBF' SIZE 104857600 AUTOEXTEND ON NEXT 20971520 
    NOLOGGING 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE USER BOGDANOVA_ADAMCHUK_RESTAURANT
    IDENTIFIED BY "Q1w2e3r4"
    default TABLESPACE BOGDANOVA_ADAMCHUK_RESTAURANT;

grant connect to BOGDANOVA_ADAMCHUK_RESTAURANT;
grant resource to BOGDANOVA_ADAMCHUK_RESTAURANT;

ALTER USER BOGDANOVA_ADAMCHUK_RESTAURANT QUOTA 100M ON BOGDANOVA_ADAMCHUK_RESTAURANT;

grant all privileges to BOGDANOVA_ADAMCHUK_RESTAURANT;
 
